import{S as L,a as b,i as n}from"./assets/vendor-c493984e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const M=document.querySelector("ul.gallery"),v=new L(".gallery-item a",{className:"js-lightbox",overlayOpacity:.8,captionsData:"alt",captionDelay:250});function h(s){const e=s.map(({webformatURL:a,largeImageURL:i,tags:t,likes:o,views:l,comments:y,downloads:f})=>`<li class="gallery-item">
	<a class="gallery-link" href="${i}">
		<img
			class="gallery-image"
			src="${a}"
			alt="${t}"
			/>
    <div class="image-stats">
  <p>Likes </br> ${o}</p>
  <p> Views </br> ${l}</p>
  <p>Comments </br> ${y}</p>
  <p>Dowloads </br> ${f}</p>
</div>
	</a>
</li>`).join("");M.insertAdjacentHTML("beforeend",e),v.refresh()}async function p(s,e,a){return(await b.get("https://pixabay.com/api/",{params:{key:"45077643-3bb964d60cb084522e3de8d92",page:e,per_page:a,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const r={searchForm:document.querySelector(".search-form"),gallery:document.querySelector("ul.gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-button")};r.searchForm.addEventListener("submit",w);const u=15;let c,d,m;async function w(s){if(s.preventDefault(),r.gallery.innerHTML="",c=1,r.loader.classList.remove("hidden"),r.loadMoreBtn.classList.add("hidden"),d=s.target.elements.search.value.trim().toLowerCase(),!d){r.loader.classList.add("hidden"),n.info({message:"Please enter search text!",position:"topRight",timeout:2e3}),s.currentTarget.reset();return}try{const e=await p(d,c,u);if(h(e.hits),e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3,icon:""});return}m=Math.ceil(e.totalHits/u),m>1?(r.loadMoreBtn.classList.remove("hidden"),r.loadMoreBtn.addEventListener("click",g)):r.loadMoreBtn.classList.add("hidden")}catch(e){n.error({message:`Request failed with: ${e}`,position:"topRight",timeout:2e3})}finally{s.target.reset(),r.loader.classList.add("hidden")}}async function g(s){r.loadMoreBtn.classList.add("hidden"),r.loader.classList.remove("hidden");try{const e=await p(d,c,u);h(e.hits),c+=1}catch(e){n.error({message:`Request failed with: ${e}`,position:"topRight",timeout:2e3})}finally{r.loader.classList.add("hidden");const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,left:0,behavior:"smooth"}),c===m?(r.loadMoreBtn.classList.add("hidden"),n.info({message:"We`re sorry, but you`ve reached the end of search results.",position:"topRight",timeout:2e3,icon:""}),r.loadMoreBtn.removeEventListener("click",g)):r.loadMoreBtn.classList.remove("hidden")}}
//# sourceMappingURL=commonHelpers.js.map
