import{S as h,a as y,i as c}from"./assets/vendor-c493984e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const n of a.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(t){if(t.ep)return;t.ep=!0;const a=i(t);fetch(t.href,a)}})();const f=document.querySelector("ul.gallery"),L=new h(".gallery-item a",{className:"js-lightbox",overlayOpacity:.8,captionsData:"alt",captionDelay:250});function d(s){const e=s.map(({webformatURL:i,largeImageURL:l,tags:t,likes:a,views:n,comments:g,downloads:p})=>`<li class="gallery-item">
	<a class="gallery-link" href="${l}">
		<img
			class="gallery-image"
			src="${i}"
			alt="${t}"
			/>
    <div class="image-stats">
  <p>Likes </br> ${a}</p>
  <p> Views </br> ${n}</p>
  <p>Comments </br> ${g}</p>
  <p>Dowloads </br> ${p}</p>
</div>
	</a>
</li>`).join("");f.insertAdjacentHTML("beforeend",e),L.refresh()}async function u({searchText:s,page:e,perPage:i}){return(await y.get("https://pixabay.com/api/",{params:{key:"45077643-3bb964d60cb084522e3de8d92",page:e,per_page:i,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const r={searchForm:document.querySelector(".search-form"),gallery:document.querySelector("ul.gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-button")};r.searchForm.addEventListener("submit",b);const o={perPage:15,page:1,searchText:"",totalPages:0};async function b(s){if(s.preventDefault(),r.gallery.innerHTML="",o.page=1,r.loader.classList.remove("hidden"),r.loadMoreBtn.classList.add("hidden"),o.searchText=s.target.elements.search.value.trim().toLowerCase(),!o.searchText){r.loader.classList.add("hidden"),c.info({message:"Please enter search text!",position:"topRight",timeout:2e3}),s.currentTarget.reset();return}try{const e=await u(o);if(d(e.hits),e.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3,icon:""});return}o.totalPages=Math.ceil(e.totalHits/o.perPage),o.totalPages>1?(r.loadMoreBtn.classList.remove("hidden"),r.loadMoreBtn.addEventListener("click",m)):r.loadMoreBtn.classList.add("hidden")}catch(e){c.error({message:`Request failed with: ${e}`,position:"topRight",timeout:2e3})}finally{s.target.reset(),r.loader.classList.add("hidden")}}async function m(s){r.loadMoreBtn.classList.add("hidden"),r.loader.classList.remove("hidden");try{const e=await u(o);d(e.hits),o.page+=1}catch(e){c.error({message:`Request failed with: ${e}`,position:"topRight",timeout:2e3})}finally{r.loader.classList.add("hidden");const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,left:0,behavior:"smooth"}),o.page===o.totalPages?(r.loadMoreBtn.classList.add("hidden"),c.info({message:"We`re sorry, but you`ve reached the end of search results.",position:"topRight",timeout:2e3,icon:""}),r.loadMoreBtn.removeEventListener("click",m)):r.loadMoreBtn.classList.remove("hidden")}}
//# sourceMappingURL=commonHelpers.js.map
